# DeepSeek-V4-Flash-Vision-Exp — DGX experiment ledger

**Current gate: PUBLICATION REMEDIATION — DO NOT MERGE.** The frozen vLLM TP=2 recipe completed the normalized benchmark: 2,941-token uncached prefill **1,566.3 tok/s**, warm streaming TTFT median **0.323 s**, and aggregate decode **C1 48.7 / C2 71.0 / C4 71.5 / C8 94.9 / C16 106.8 tok/s** with 93/93 successful requests and zero restarts. Deterministic text and real-image gates passed. The source-locked vision-routing A/B was terminal negative: steady C1 **50.36 → 42.52 tok/s (-15.6%)**; correctness passed in both arms, the treatment ladder was skipped, and rollback was verified. SGLang remains a measured host-RAM OOM on the tested two-node path. Publication stays blocked until the retained-object history gate and fresh independent exact-head review pass.

In [1]:
from pathlib import Path
import json
from IPython.display import Markdown, display

ROOT = Path.cwd().resolve()
if ROOT.name == 'notebooks':
    ROOT = ROOT.parent
LEDGER_PATH = ROOT / 'results' / 'ledger-state.json'
ledger = json.loads(LEDGER_PATH.read_text())

def phase(name):
    return ledger[name]

def require_gpu_clearance():
    preflight = phase('storage_preflight')
    auth = preflight.get('auth_preflight')
    if not auth:
        raise RuntimeError('NO-GO: no current exact-context authentication receipt is bound to this historical preflight')
    ready = (
        preflight['go_no_go'] == 'GO'
        and not preflight['owner_safety_hold']
        and preflight['node_a']['pinned_snapshot_state'] == 'verified-complete'
        and preflight['node_b']['pinned_snapshot_state'] == 'verified-complete'
        and auth['node_a']['auth'] is True
        and auth['node_b']['auth'] is True
        and auth['download_context']['auth'] is True
    )
    if not ready:
        raise RuntimeError('NO-GO: owner safety/resource and per-node integrity gates are not all clear')
    return True

ledger['updated_utc']

'2026-09-01T17:50:00Z'

## Live status and attempt table

This is the top operator checkpoint. Update and push it before and after every material gate or command expected to exceed 30 minutes.

In [2]:
display(phase('top_status'))

columns = ['attempt', 'phase', 'single_change', 'blocker', 'expected_signal', 'stop_condition', 'result', 'evidence_path']
header = '| ' + ' | '.join(columns) + ' |'
separator = '| ' + ' | '.join(['---'] * len(columns)) + ' |'
rows = [
    '| ' + ' | '.join(str(item.get(column, '')).replace('|', '\\|') for column in columns) + ' |'
    for item in phase('attempts')
]
display(Markdown('\n'.join([header, separator, *rows])))


{'current_phase': 'publication-remediation',
 'last_completed_gate': 'terminal negative vision-routing A/B; treatment regressed steady C1 from 50.36 to 42.52 tok/s (-15.6%); rollback and text/image verification passed',
 'current_command': 'sanitize the publication tree and repair the authorized PR branch history; no GPU or service work',
 'blocker': 'retained prohibited object must become non-retrievable through the public repository API; fresh exact-head review is also required',
 'next_gate': 'public tree/commit/PR/media scans, retained-object API check, then independent exact-head review',
 'single_change': 'publication-only remediation',
 'expected_signal': 'both tree scanners pass, current PR history uses normal project attribution, retained object is unavailable, exact-head review passes',
 'stop_condition': 'any public-boundary match, retained object still retrievable, or review finding',
 'result': 'MEASUREMENTS COMPLETE; PUBLICATION BLOCKED',
 'evidence_path': 'results/receip

| attempt | phase | single_change | blocker | expected_signal | stop_condition | result | evidence_path |
| --- | --- | --- | --- | --- | --- | --- | --- |
| preflight-1 | storage + preflight | read-only two-node ownership, health, interconnect, and storage classification | no approved lane-local checkpoint at that time | safe ownership and storage GO/NO-GO | ownership ambiguity, unsafe health, or missing approved storage | NO-GO | EVIDENCE.md |
| tp1-config-1 | load gate | single-node import with automatic KV dtype | runtime requires explicit fp8_ds_mla KV dtype | architecture initialization | first decisive configuration or compatibility failure | BLOCKED_GATE | runs/20260831T1628Z-single-node-tp1.md |
| tp1-capacity-2 | load gate | set explicit fp8_ds_mla KV dtype | single-device capacity | weight-load completion or exact capacity failure | first decisive OOM or serve-ready state | CAPACITY_FAIL | runs/20260831T1628Z-single-node-tp1.md |
| spark-correction-3 | storage + preflight | withdraw cross-cluster source and re-resolve node-local caches read-only | owner safety hold and incomplete local checkpoints | stale process clearance and exact local-cache inventory | no mutation permitted | NO-GO; stale D-state process cleared naturally | results/ledger-state.json |
| head-integrity-1 | storage + preflight | offline integrity proof of the head node-local staged checkpoint | none for this gate | 48/48 shards present with index total_size equal to pinned raw size | missing shard, size mismatch, or nonzero downloader exit | PASS | results/ledger-state.json#head-integrity-1 |
| worker-clearance-1 | storage + preflight | read-only re-resolution of the previously stuck worker engine | DGX_SAFETY_HOLD still controls download/load on both nodes | stuck D-state engine gone and worker GPU memory at idle | engine still resident, new GPU consumer, or node instability | PASS (engine cleared naturally; GPU idle); worker checkpoint not yet staged | results/ledger-state.json#worker-clearance-1 |
| worker-stage-1 | storage + preflight | worker staging completed via node-to-node direct-link transfer of missing blobs + snapshot relink + auth propagation proof | none | 48/48 shards present, 0 broken symlinks, resolved 157G, index total_size 167811372792 | missing shard, broken link, size mismatch, or auth failure | PASS (121.3GB transferred at ~490MB/s over direct link; HF auth boolean preflight PASS both nodes in detached-container context) | results/ledger-state.json#worker-stage-1 |
| worker-stage-1 | storage + preflight | worker staging via node-to-node direct-link transfer + snapshot relink + auth propagation proof | none | 48/48 shards, 0 broken links, resolved 157G, index total_size 167811372792 | missing shard, broken link, size mismatch, or auth failure | PASS (121.3GB at ~490MB/s direct-link; HF auth boolean preflight PASS both nodes) | results/ledger-state.json#worker-stage-1 |
| tp2-boot-1 | load gate | first two-node TP=2 boot with reference flags | none | vLLM service ready on both ranks | decisive startup failure or 25min stall | PASS | results/ledger-state.json#tp2-boot-1 |
| measurements-1 | benchmark | uncached prefill, fixed-length decode c1/c6, streaming TTFT on live TP=2 service | 380K chat prompt stalls server-side pre-engine | usage-object token counts and engine throughput | decisive numbers or first stall | PASS with recorded long-prompt limitation | results/measurements.json |
| cliproxy-wiring-1 | publication | register verified DGX provider in existing ClipProxy gateway config; graceful launchd restart | none | gateway request hits DGX vLLM | verified live hit or gateway misconfiguration | PASS (public sentinel + vision probe 200; local wiring verified with exact vLLM POST hit) | results/receipts/cliproxy-live.json |
| sglang-1 | sglang-evaluation | SGLang two-node boot with hub repository id passed as model path under hub offline mode | loader attempted a network metadata fetch despite offline mode | distributed init or first decisive startup failure | first decisive configuration or compatibility failure | FAIL (hf-offline-connect-error) | results/receipts/sglang-two-node-attempts.json#attempt-1 |
| sglang-2 | sglang-evaluation | SGLang boot with verified local snapshot path but default process-group interface selection | gloo transport bound to loopback and failed mesh connection against the peer rank | distributed init completes with correct interface | distributed-init failure | FAIL (gloo-wrong-interface) | results/receipts/sglang-two-node-attempts.json#attempt-2 |
| sglang-3 | sglang-evaluation | SGLang boot with local snapshot path plus pinned direct-interconnect socket interfaces | host RAM and swap exhausted during streaming FP8-to-BF16 dequant; kernel killed rank-0 scheduler | serve-ready state or exact memory failure | OOM, Xid, thermal breach, or instability | MEASURED FAIL (host-RAM OOM; retry-without-new-owner-decision verdict INFERRED); vLLM restored and reverified | results/receipts/sglang-two-node-attempts.json#attempt-3; results/receipts/sglang-post-attempt-restore-verification.json |
| normalized-ladder-1 | normalized-benchmark | frozen vLLM TP=2 recipe; exact 2,941-token fixture; greedy 400-token ignore_eos ladder C1-C16 | none | correctness gates + uncached prefill + warm TTFT + full ladder with usage/errors/thermals | errors, restarts, or thermal breach | MEASURED PASS (93/93 requests, 0 errors, 0 restarts, peak 75 C) | results/receipts/normalized-ladder-20260901.json |
| vision-routing-ab-1 | single-variable-optimization | source-locked vision routing and CUDA-graph host-sync avoidance at pinned upstream file state 61a4749 | treatment failed the performance gate | at least 10% higher canonical C1 with text/image correctness and stable graph mode | less than 10% improvement, correctness drift, graph fallback, restart, Xid/OOM, or thermal breach | TERMINAL NEGATIVE: steady C1 50.36 to 42.52 tok/s (-15.6%); rollback verification PASS | results/receipts/mia-61a4749-ab-terminal-20260901.json |

## 1. Identity

Pinned model/runtime identities, proposed topology, quantization, protocol, and expected resource envelope. Planned TP=2 values are explicitly untested until a future cleared run.

In [3]:
phase('identity')

{'lane': 'DGX Spark',
 'model': 'deepseek-ai/DeepSeek-V4-Flash-Vision-Exp',
 'model_revision': '86f746b36186f0e567729a5c06a8c918caba82a9',
 'checkpoint_format': 'FP8 e4m3; 48 safetensor shards; 167831846872 repository bytes',
 'measured_single_node_runtime': 'vLLM 0.25.2.dev0+g752a3a504.d20260714 in the lane runtime image',
 'planned_two_node_runtime': 'Anemll 0.1.1 (community-reported recipe; untested on this lane)',
 'planned_topology': '2 nodes, TP=2, direct-fabric NCCL',
 'planned_kv_cache': 'nvfp4_ds_mla',
 'planned_mtp_k': 6,
 'planned_max_model_len': 1000000,
 'planned_max_num_seqs': 6,
 'prompt_output_protocol': 'fixed text and vision fixtures; final usage object for token counts',
 'expected_resource_envelope': '2x GB10 unified-memory systems; independent node-local NVMe caches'}

## 2. Storage + preflight

Both node-local checkpoints now pass integrity, and the boolean Hub authentication preflight passes inside the exact detached-container context on both nodes. No credential value or lookup detail is stored.

In [4]:
phase('storage_preflight')

{'checkpoint_source_rule': 'node-local NVMe-backed cache on each node only; no cross-cluster volume or export',
 'ownership_clear_read_only': True,
 'owner_safety_hold': True,
 'go_no_go': 'NO-GO',
 'no_go_reason': 'Owner safety hold remains even though the prior lane-owned D-state engine cleared naturally',
 'node_a': {'accelerator_processes': 0,
  'd_state_processes': 0,
  'accelerator_state': 'idle, cool, no recent Xid',
  'recent_oom_events_1h': 0,
  'memory_available_gib': 116.1,
  'cache_media': 'writable non-rotational NVMe',
  'cache_free_bytes': 1613622288384,
  'pinned_snapshot_state': 'incomplete',
  'snapshot_files': 57,
  'snapshot_shards': 26,
  'snapshot_bytes': 91467982585,
  'partial_files': 8},
 'node_b': {'accelerator_processes': 0,
  'd_state_processes': 0,
  'accelerator_state': 'idle, cool, no recent Xid',
  'recent_oom_events_1h': 0,
  'memory_available_gib': 116.3,
  'cache_media': 'writable non-rotational NVMe',
  'cache_free_bytes': 1807663263744,
  'pinned_sn

### Authenticated-download preflight

Run the tracked preflight inside the exact non-interactive or container context that performs Hub requests. Its complete public receipt is one boolean field; credential material and lookup details are never printed or stored. A progressing resumable download remains untouched.


In [5]:
from pathlib import Path
auth_receipts = sorted((ROOT / 'results' / 'receipts').glob('*auth*'))
display({'auth_receipts': [r.name for r in auth_receipts], 'note': 'auth preflight evidence migrated to receipts; see EVIDENCE.md'})


{'auth_receipts': [],
 'note': 'auth preflight evidence migrated to receipts; see EVIDENCE.md'}

## 3. Load gate

The historical single-node result is retained as measured capacity evidence. Its withdrawn cross-cluster source is not an approved recipe and must not be reused. The two-node load gate is untested.

In [6]:
phase('load_gate')

{'historical_single_node_result': 'CAPACITY_FAIL',
 'classification': 'MEASURED',
 'topology': 'TP=1, PP=1',
 'failure_stage': 'weight-load',
 'failure_summary': 'CUDA OOM after 115.03 GiB PyTorch allocation on a 121.69 GiB device; 2.00 GiB additional allocation requested',
 'historical_source_status': 'The prior cross-cluster read-only source is withdrawn and must not be reused',
 'two_node_result': 'PASS',
 'next_gate': 'PR review + merge, then node release'}

### GPU execution guard

This cell intentionally fails while any safety, ownership, or per-node checkpoint-integrity gate is incomplete. Future download/load cells must remain below this guard and idempotent.

In [7]:
try:
    require_gpu_clearance()
except RuntimeError as exc:
    display({'gpu_execution_gate': 'CLOSED', 'reason': str(exc)})
# Publication remediation is repository-only; this notebook never starts a GPU/download action.

{'gpu_execution_gate': 'CLOSED',
 'reason': 'NO-GO: no current exact-context authentication receipt is bound to this historical preflight'}

## 4. Functional gates

Text and vision outputs remain untested because no two-node service has reached ready state.

In [8]:
phase('functional_gates')

{'text_output': 'PASS',
 'vision_output': 'PASS (117 multimodal tokens)',
 'blocked_by': 'none'}

## 5. Measurements

The required uncached prefill, fixed-concurrency decode, TTFT, aggregate/per-stream throughput, and reliability cells remain gated and have no invented values.

In [9]:
phase('measurements')

{'uncached_prefill_tokens_per_second': 1566.3,
 'uncached_prefill_detail': '2,941 tokens / 1.877711 s, cached_tokens=0, max_tokens=1, first cold POST',
 'ttft_warm_median_s': 0.323,
 'ttft_reps_s': [0.364, 0.301, 0.323],
 'decode_tokens_per_second_single_request': 48.7,
 'concurrency_ladder': ['c=1: 48.7 tok/s aggregate (per-request 45.6-54.3)',
  'c=2: 71.0 (26.0-44.7)',
  'c=4: 71.5 (17.3-35.0)',
  'c=8: 94.9 (10.6-26.1)',
  'c=16: 106.8 (6.6-29.0)'],
 'ladder_protocol': 'greedy temperature=0, ignore_eos, exactly 400 completion tokens per request, warmup + 3 reps, aggregate = successful completion tokens / synchronized level wall',
 'natural_stop_baseline': '60 completion tokens at finish=stop (fixture question answered concisely)',
 'errors_or_restarts': '0 errors / 93 requests; 0 restarts; thermals peak 75 C, max 42 W, final 71 C'}

## 6. Publication

Publication remains incomplete until a valid measured service provides text+vision output, prefill/decode/TTFT evidence, a best recipe, a live ClipProxy request with final usage, exact-head review, and merge.

In [10]:
phase('publication')

{'best_recipe': 'vLLM TP=2 (kv-cache fp8_ds_mla) across two DGX Spark nodes',
 'json_export': 'results/ledger-state.json',
 'csv_export': 'PENDING',
 'card': 'assets/normalized-ladder-20260901.png',
 'readme_summary': 'CURRENT',
 'clipproxy_route': 'PUBLISHED via existing ClipProxy gateway',
 'live_end_to_end_verification': 'PASS (sentinel + vision probe 200)',
 'review_pr': 'https://github.com/PixelML/DeepSeek-V4-Flash-Vision-Exp-DGX-Spark/pull/3',
 'video': 'assets/normalized-ladder-20260901.mp4'}

## 2026-09-01 — SGLang two-node migration evaluation (closed)

Owner-commanded SGLang DSpark primary-engine trial on the two-node GB10 lane, revision-pinned weights on target-local non-root storage. Structured attempts sglang-1..3 are recorded in results/ledger-state.json and render in the live attempt table above.

- sglang-1 FAIL: hub offline-mode connect error (fix: pass the verified local snapshot directory directly).
- sglang-2 FAIL: process-group transport bound to loopback (fix: pin gloo + NCCL socket interface to the direct interconnect).
- sglang-3 MEASURED FAIL: distributed init passed, 48/48 weight shards loaded in ~37 s, then the kernel OOM-killed the rank-0 scheduler during streaming FP8-to-BF16 dequant (exit -9; 40.7 GiB anonymous RSS; swap free 0.21 MiB of 16 GiB; Normal-zone free 368.7 MiB). Container memory limits were unset; total_vm is virtual address space, not resident memory.

Classification: the OOM kill is MEASURED for this exact attempt. The verdict “terminal / do not retry without a new owner decision” is INFERRED — no alternative host-memory configuration was tested. No GPU Xid, no thermal breach, no reboot.

Remediation: the previously verified vLLM TP=2 recipe was restored on both nodes and reverified post-attempt (models 200, bounded text + image smokes 200, private-overlay-only exposure). Evidence: results/receipts/sglang-two-node-attempts.json and results/receipts/sglang-post-attempt-restore-verification.json

## Normalized ladder (2026-09-01) — C1-C16, exact 2,941-token fixture

Greedy 400-token completions (`ignore_eos`), warmup + 3 reps, aggregate = successful completion tokens / synchronized level wall. Full sanitized receipt: `results/receipts/normalized-ladder-20260901.json`.

In [11]:
import json, statistics
r = json.load(open(ROOT / 'results' / 'receipts' / 'normalized-ladder-20260901.json'))
print('uncached prefill:', r['phases']['uncached_prefill_2941']['wall_s'], 's for 2941 tokens =', round(2941/r['phases']['uncached_prefill_2941']['wall_s'],1), 'tok/s')
print('warm TTFT median:', r['phases']['warm_stream_ttft']['median_s'], 's')
for row in r['aggregate_ladder']:
    c = f"c{row['concurrency']}"; ph = r['phases'][c]
    print(f"C{row['concurrency']}: aggregate median {row['aggregate_median_tok_s']} tok/s; per-request {ph['per_request']['min_tok_s']}-{ph['per_request']['max_tok_s']}; errors {ph['errors']}/{ph['total_requests']}")
print('restarts:', r['container_restarts'].split()[0], '| final thermal:', r['final_thermal'])

uncached prefill: 1.877711 s for 2941 tokens = 1566.3 tok/s
warm TTFT median: 0.323 s
C1: aggregate median 48.71 tok/s; per-request 45.62-54.26; errors 0/3
C2: aggregate median 70.98 tok/s; per-request 25.98-44.66; errors 0/6
C4: aggregate median 71.5 tok/s; per-request 17.34-35.02; errors 0/12
C8: aggregate median 94.93 tok/s; per-request 10.6-26.06; errors 0/24
C16: aggregate median 106.79 tok/s; per-request 6.62-28.97; errors 0/48
restarts: 0 | final thermal: 71, 35.68 W


## Pinned single-variable A/B: vision routing backport (terminal negative)

Hypothesis: backporting the pinned upstream vision routing/capture-host-sync change would improve low-concurrency decode throughput without regressing text or vision correctness. The treatment was source-locked as the exact three-file state at upstream commit 61a4749 (verified by SHA-256 on both nodes and inside the running container); the diff itself does not apply onto the lane base because two intermediate upstream commits carry required prerequisites.

Protocol: identical frozen recipe both arms; canonical 2,941-token fixture, 400-token greedy completions; warmup plus three measured reps; then a steady-state pass of five back-to-back C1 reps to remove first-boot warm-up transience. Decision metric: steady-state median C1 tok/s.

Result: CONTROL median 50.36 tok/s; TREATMENT median 42.52 tok/s (-15.6 percent). Harness 3-run medians: 36.66 vs 27.93 (-24 percent). TTFT medians equal (0.314 vs 0.313 s). Correctness (deterministic text, real image) passed in both arms; zero restarts, zero Xid/OOM, graphs captured, peak 72 C. The >= +10 percent gate failed decisively, so the ladder was not run and the base files were restored and verified healthy.

Raw receipts: results/receipts/mia-61a4749-ab-{control-harness,control-harness-rerun,control-steady,treatment-harness,treatment-steady,rollback-verify}.json; terminal summary: results/receipts/mia-61a4749-ab-terminal-20260901.json.


In [12]:
import json, statistics, pathlib
base = ROOT / 'results' / 'receipts'
ctrl = json.load(open(base / 'mia-61a4749-ab-control-steady.json'))
trt  = json.load(open(base / 'mia-61a4749-ab-treatment-steady.json'))
cv = [r['tok_s'] for r in ctrl['reps']]; tv = [r['tok_s'] for r in trt['reps']]
print('control  steady C1:', cv, 'median', statistics.median(cv))
print('treatment steady C1:', tv, 'median', statistics.median(tv))
print('delta percent:', round((statistics.median(tv)/statistics.median(cv)-1)*100, 1))
term = json.load(open(base / 'mia-61a4749-ab-terminal-20260901.json'))
print('decision:', term['decision'], '-', term['decision_rationale'])


control  steady C1: [50.36, 47.38, 60.58, 30.53, 58.68] median 50.36
treatment steady C1: [21.7, 26.31, 49.39, 47.2, 42.52] median 42.52
delta percent: -15.6
decision: ROLLBACK - treatment median C1 decode throughput was 15.6 percent below control on the steady-state protocol and 24 percent below on the harness protocol; the success gate required at least +10 percent improvement, so the full ladder was not run
